# Generated by Django 5.0.3 on 2024-03-18 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_alter_class_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='established_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='section',
            name='name',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=2),
        ),
        migrations.AlterField(
            model_name='staff',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='email',
            field=models.EmailField(blank=True, max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='employment_type',
            field=models.CharField(choices=[('regular', 'Regular'), ('ssa', 'SSA'), ('guest', 'Guest'), ('hkrnl', 'HKRNL'), ('nsqf', 'NSQF'), ('other', 'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='staff',
            name='joining_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='retirement_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
