# Generated by Django 5.0.3 on 2024-03-27 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staff',
            old_name='phone_number',
            new_name='designation',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='school',
        ),
        migrations.AddField(
            model_name='staff',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
