# Generated by Django 5.0.3 on 2024-03-19 15:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday')], max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='timetableslot',
            name='day',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms.day'),
        ),
    ]
