# Generated by Django 5.0.3 on 2024-03-21 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_alter_student_address_line1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='family_annual_income',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='father_highest_qualification',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='mother_pan',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='student',
            name='school_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='school_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
