# Generated by Django 5.0.3 on 2024-03-28 16:22

import django.db.models.deletion
import django.db.models.expressions
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_alter_staff_teaching_subject_1'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Staff', to='cms.subject'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='teaching_subject_1',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='teachers',
            field=models.ManyToManyField(blank=True, limit_choices_to={'subject__in': django.db.models.expressions.OuterRef('subject')}, to='cms.staff'),
        ),
    ]
