# Generated by Django 5.0.3 on 2024-04-25 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_student_subjects'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='qualification',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
