# Generated by Django 5.0.3 on 2024-03-21 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0003_alter_student_family_annual_income_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='mother_highest_qualification',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='mother_pan',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
