# Generated by Django 5.0.3 on 2024-04-25 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0003_staff_qualification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='name',
            field=models.CharField(choices=[('None', 'None'), ('Hindi', 'Hindi'), ('English', 'English'), ('Social Studies', 'Social Studies'), ('Science', 'Science'), ('Math', 'Math'), ('Punjabi', 'Punjabi'), ('Computer', 'Computer'), ('Home Science', 'Home Science'), ('Physics', 'Physics'), ('Chemistry', 'Chemistry'), ('Account', 'Account'), ('Business', 'Business'), ('Political Science', 'Political Science'), ('Economics', 'Economics'), ('Geography', 'Geography'), ('Psychology', 'Psychology'), ('Physical Education', 'Physical Education'), ('Music', 'Music'), ('Automobile', 'Automobile'), ('Beauty & Wellness', 'Beauty & Wellness'), ('Biology', 'Biology'), ('Sanskrit', 'Sanskrit'), ('Fine Arts', 'Fine Arts')], max_length=100, unique=True),
        ),
    ]
