# Generated by Django 5.0.3 on 2024-04-25 16:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0004_alter_subject_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='school',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff', to='cms.school'),
        ),
    ]
