# Generated by Django 5.0.3 on 2024-03-26 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0004_alter_student_admission_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='disability',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
