# Generated by Django 5.0.3 on 2024-03-27 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0004_alter_staff_employee_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='designation',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
