# Generated by Django 5.0.3 on 2024-05-04 04:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0006_student_bpl_certificate_issuing_authority'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField()),
            ],
        ),
        migrations.AlterField(
            model_name='timetableslot',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='timetableslot',
            name='period',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='timetableslot',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='DailyTimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(blank=True, choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], max_length=10, null=True)),
                ('end_time', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='end_time', to='cms.timeslot')),
                ('start_time', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='start_time', to='cms.timeslot')),
            ],
            options={
                'verbose_name': 'Daily Time Slot',
                'verbose_name_plural': 'Daily Time Slots',
            },
        ),
    ]
