# Generated by Django 5.0.3 on 2024-05-04 05:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0007_timeslot_alter_timetableslot_end_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailytimeslot',
            name='end_time',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='end_time', to='cms.timeslot'),
        ),
        migrations.AlterField(
            model_name='dailytimeslot',
            name='start_time',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='start_time', to='cms.timeslot'),
        ),
    ]
