# Generated by Django 5.0.3 on 2024-05-06 06:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0009_subjectteacherassignment_teachersubjectallocation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjectteacherassignment',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms.staff', to_field='employee_id'),
        ),
    ]
