# Generated by Django 5.0.3 on 2024-04-27 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0009_alter_timeslot_day_alter_timeslot_end_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetableslot',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='timetableslot',
            name='period',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='timetableslot',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
