# Generated by Django 5.0.3 on 2024-05-06 08:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0010_alter_subjectteacherassignment_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff', to='cms.school'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Staff', to='cms.subject'),
        ),
    ]
